# Generated by Django 3.2.7 on 2021-09-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACM', '0002_auto_20210912_0747'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='root',
            table='Root',
        ),
    ]
